version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: dd_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    image: ${DOCKER_USERNAME}/mean-backend:latest
    container_name: backend
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://mongodb:27017/dd_db
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    image: ${DOCKER_USERNAME}/mean-frontend:latest
    container_name: frontend
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge