name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: nantha01/mean-backend:latest
    
    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: nantha01/mean-frontend:latest
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo apt update
          sudo apt install -y docker.io docker-compose
          sudo usermod -aG docker ubuntu
          sudo mkdir -p /opt/mean-app
          cd /opt/mean-app
          sudo wget https://raw.githubusercontent.com/Deadends/crud-dd-task-mean-app/main/docker-compose.prod.yml
          sudo wget https://raw.githubusercontent.com/Deadends/crud-dd-task-mean-app/main/nginx/nginx.conf -P nginx/
          sudo DOCKER_USERNAME=nantha01 docker-compose -f docker-compose.prod.yml up -d